preprocessing:
  categorical_columns: [
    'sex', 'anatom_site_general', 'tbp_tile_type',
    'tbp_lv_location', 'tbp_lv_location_simple'

  ]

training:
  target: 'target'
  features: [
    'age_approx', 'sex', 'anatom_site_general',
    'clin_size_long_diam_mm',
    'tbp_lv_A', 'tbp_lv_Aext',
    'tbp_lv_B', 'tbp_lv_Bext',
    'tbp_lv_C', 'tbp_lv_Cext',
    'tbp_lv_H', 'tbp_lv_Hext',
    'tbp_lv_L', 'tbp_lv_Lext',
    'tbp_lv_areaMM2', 'tbp_lv_area_perim_ratio', 'tbp_lv_color_std_mean',
    'tbp_lv_deltaA', 'tbp_lv_deltaB', 'tbp_lv_deltaL', 'tbp_lv_deltaLBnorm',
    'tbp_lv_eccentricity', 'tbp_lv_location', 'tbp_lv_location_simple',
    'tbp_lv_minorAxisMM', 'tbp_lv_nevi_confidence', 'tbp_lv_norm_border', 'tbp_lv_norm_color',
    'tbp_lv_perimeterMM', 'tbp_lv_radial_color_std_max', 'tbp_lv_stdL', 'tbp_lv_stdLExt',
    'tbp_lv_symm_2axis', 'tbp_lv_symm_2axis_angle',

    'lesion_diameter_ratio', 'lesion_diameter_difference',

    #'patient_lesion_count'
  ]
  categorical_features: []
  folds: [1, 2, 3, 4, 5]
  seeds: [42]

model_parameters:
  num_leaves: 128
  learning_rate: 0.01
  bagging_fraction: 0.9
  bagging_freq: 1
  feature_fraction: 0.9
  feature_fraction_bynode: 0.9
  min_data_in_leaf: 100
  min_gain_to_split: 0.
  lambda_l1: 0.
  lambda_l2: 0.
  max_bin: 255
  max_depth: -1
  boost_from_average: True
  objective: 'binary'
  scale_pos_weight: 1
  metric: 'binary_logloss'
  seed: null
  feature_fraction_seed: null
  bagging_seed: null
  drop_seed: null
  data_random_seed: null
  boosting_type: 'gbdt'
  verbose: 1
  n_jobs: 16

fit_parameters:
  boosting_rounds: 400
  log_evaluation: 50